# Generated by Django 4.0.3 on 2022-04-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_kongjian_delete_qq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kongjian',
            new_name='qq_kongjian',
        ),
    ]
