# Generated by Django 4.0.3 on 2022-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message_sender',
            new_name='username',
        ),
    ]
