# Generated by Django 4.0.6 on 2022-07-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='id',
        ),
    ]
